name: Build ESPHome Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile all yaml
        run: |
          for file in *.yaml; do
            esphome compile "$file"
          done

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esphome-firmware
          path: |
            ./**/.esphome/build/*/.pio/build/*/*.bin
